### ISSUE TITLE
Master branch failed with : 'Config' object has no attribute 'get_disks_id_exclude'

### ISSUE THREAD

**Issue by kobihk** [wefixit-AT/oVirtBackup#86]
@wefixit-AT could you please revert PR #83  from master and merge it to ovirt4.3?

because PR #83 depends on PR #70 which merged to branch ovirt4.3.

now in master branch, I got the following error:
!!! Got unexpected exception: 'Config' object has no attribute 'get_disks_id_exclude'

**Comment by GMasta2000** [comment]
> @wefixit-AT could you please revert PR #83 from master and merge it to ovirt4.3?
> 
> because PR #83 depends on PR #70 which merged to branch ovirt4.3.
> 
> now in master branch, I got the following error: !!! Got unexpected exception: 'Config' object has no attribute 'get_disks_id_exclude'

You need to add a parameter to config, an example is in config_example.cfg
`# an array of exclude disks id,exampel ["6d811aa25-52a1-45c3-9f40-1c7c868182c9","6e78d7c2-5786-4dz2-a966-fd308c23f08e"]`
`disks_id_exclude: []`

Sorry, I did not understand the question immediately, you are right, in the branch Master these changes are not.

**Comment by Dankhatskevich** [comment]
Hi, I add disks_id_exclude: [] to config file. But it doesn't fix. I still face error !!! Got unexpected exception: 'Config' object has no attribute 'get_disks_id_exclude'.

**Comment by Dankhatskevich** [comment]
A little update. Your master branch does not contain info in config.py about disks_id_exclude: [], also there is no mention about it in config_example.cfg.  But they exist in 4.3 branch.

**Comment by kobihk** [comment]
Hi @Dankhatskevich 
This issue should be fixed in:
https://github.com/wefixit-AT/oVirtBackup/pull/87
Please try to use it

**Comment by micallef8088** [comment]
Hello everyone, I can't get the script to work on version 4.5.4 gives the same error 'Config' object has no attribute 'get_disks_id_exclude'

Update №1

I don’t know how to use python script, I found changes in #87, tried to fix it, backup script is started, snapshot is taken, VM is deployed from snapshot, but I don’t transfer to NFS, error "DEBUG: Fault reason is "Operation Failed". Fault detail is " [Cannot export VM. The specified domain 'BackUps' is not an export domain.]". HTTP response code is 400."

Update №2


I figured out what the error was, a data domain was created instead of export. Sorry.

But there is one more mistake, it does not parse the name in the config file, I give it the full name, it ignores and simply backups everything according to the list of all VMs.

Update №3

Thank you, you are the best!!111 solved all the problems xD
